version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_grupo_nach
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: grupo_nach_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always
